import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header className="sticky top-0 z-20 w-full bg-white/80 dark:bg-zinc-900/80 border-b border-zinc-200 dark:border-zinc-800 shadow-sm flex items-center justify-center h-16 px-4">
          <div className="flex items-center gap-2">
            <span className="font-bold text-xl tracking-tight flex items-center gap-2">
              <Link href={"/"}>
                <ShoppingBag />
              </Link>
              ESTATE SALE
            </span>
          </div>
        </header> */}
        <NavBar />
        {children}
      </body>
    </html>
  );
}
